### PR TITLE
--version 1.4 not 1.0

### PR DESCRIPTION
**Pull request by tokiAi**
Hi,
was surprised when entering --version that it was displayed version 1.0 and not 1.4. And that's why I "make/make install" the library twice.
You can either pull or make the small change yourself. Maybe there is also an automatic way to update the version.

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
Thanks! I chose to just remove the hardcoded version number, the `GIT_VERSION` includes tag name.

**Comment by tokiAi** [comment]
Hi,
"--version" now empty

I tested it on MacOS and Ubuntu 18.04

`$ focus-stack --version`
```
focus-stack , built Sep  3 2022 19:02:28
Compiled with OpenCV version 4.6.0
Copyright (c) 2019 Petteri Aimonen
```

GIT_VERSION doesn't work?

**Comment by PetteriAimonen** [comment]
Are you building from a git checkout or from the downloaded source code package?

**Comment by tokiAi** [comment]
I think, i build it "from the downloaded source code package" (see below). 
Does the behavior change if I do it via `git-clone`?

I tested it twice - instead of "GIT_VERSION"  it's empty:

- once from:  [img_test_1](https://github.com/tokiAi/focus-stack/blob/master/1.png) (because it's the version changed with the last commit)
- second from:  [img_test_2](https://github.com/tokiAi/focus-stack/blob/master/2.png)

and then cd to the folder and "make" "make install" 

(on mac I needed to delete "-D" in Makefile "install -D build/focus-stack")

**Pull request closed without merging**
